apiVersion: v1
kind: Service
metadata:
  name: aks-demo-service
  namespace: demo-app
  labels:
    app: aks-demo
spec:
  type: LoadBalancer    # 외부에서 접근 가능한 Public IP 생성
  ports:
  - port: 80            # 외부 포트
    targetPort: 8080    # 컨테이너 포트
    protocol: TCP
    name: http
  selector:
    app: aks-demo
